# Site settings
title: Блог Гуватары
header-img: img/home-bg.jpg
email: guvatara@gmail.com
copyright_name: Guvatara
description: "Немного обо всем, что меня задело"
baseurl: ""
url: "http://guvatara.com"
twitter_username: Guvatara
github_username:  guvatara
facebook_username:  guvatara
email_username:  guvatara@gmail.com

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: guvataragithub

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-75473648-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 7
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
